### ISSUE TITLE
Issue with iota node 

### ISSUE THREAD

**Issue by Ayahatemallam223** [SuryaAssistant/iota-raspberrypi-gateway#3]
https://api.lb-0.h.chrysalis-devnet.iota.cafe 
cannot connect to this node 

This error 
main.py
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NodeError("Couldn't get a result from any node")', src/client/mod.rs:153:84
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/thonny/plugins/cpython/__main__.py", line 43, in <module>
    MainCPythonBackend(target_cwd).mainloop()
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 72, in mainloop
    self._handle_normal_command(msg)
  File "/usr/lib/python3/dist-packages/thonny/plugins/cpython/cpython_backend.py", line 228, in _handle_normal_command
    response = handler(cmd)
  File "/usr/lib/python3/dist-packages/thonny/plugins/cpython/cpython_backend.py", line 404, in _cmd_Run
    return self._execute_file(cmd, SimpleRunner)
  File "/usr/lib/python3/dist-packages/thonny/plugins/cpython/cpython_backend.py", line 851, in _execute_file
    result_attributes = self._execute_source(
  File "/usr/lib/python3/dist-packages/thonny/plugins/cpython/cpython_backend.py", line 865, in _execute_source
    return self._current_executor.execute_source(
  File "/usr/lib/python3/dist-packages/thonny/plugins/cpython/cpython_backend.py", line 1283, in execute_source
    return self._execute_prepared_user_code(statements, global_vars)
  File "/usr/lib/python3/dist-packages/thonny/plugins/cpython/cpython_backend.py", line 1238, in wrapper
    result = method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/thonny/plugins/cpython/cpython_backend.py", line 1225, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/thonny/plugins/cpython/cpython_backend.py", line 1295, in _execute_prepared_user_code
    exec(statements, global_vars)
  File "/home/pi1/iota-raspberrypi-gateway/src/main.py", line 256, in <module>
    client = iota_client.Client(nodes_name_password=[[chrysalis_url]])
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: NodeError("Couldn't get a result from any node")

Backend terminated or disconnected. Use 'Stop/Restart' to restart.

**Comment by SuryaAssistant** [comment]
Hi,
The chrysalis devnet has been deactivated by IOTA. That's why you can't connect to the URL and all of this repository is not updated yet. Please go to the newest IOTA documentation for "IOTA SDK".

If you are using python, please check this pages
Installation : https://github.com/iotaledger/iota-sdk/tree/develop/bindings/python
Endpoints : https://wiki.iota.org/build/networks-endpoints
